feat: use new fonts in old components
curvefi/curve-frontend pull request #476
Opened 2024-11-26 16:20 UTC by DanielSchiavini

- Use mona sans as default font
- Use minecraft as default monospace font
- Use hubot sans as default font in chad mode

2024-11-27 15:00 UTC, 0xtutti approved these changes

2024-11-27 15:12 UTC, OnlyJousting approved these changes

2024-12-05 11:47 UTC, OnlyJousting submitted a review, later dismissed

2024-12-05 15:57 UTC, 0xAlunara requested changes
In general the PR looks fine, *however*, between the opening of the PR and now the DAO app has also been merged into main, thus you'd have to apply the same changes to the new DAO app.

Remove the commodore font, modify its `globalStyle.ts`, `globals.css`, `_app.tsx` and `_document.tsx` in similar fashion as you did for the other 3 apps.

2024-12-05 15:57 UTC, 0xAlunara commented on apps/loan/src/pages/_app.tsx
> -  const initOnboardApi = useCallback(
Unrelated to the PR's goal, but it's an unused callback so it's fine.

2024-12-05 15:57 UTC, 0xAlunara commented on apps/loan/src/utils/helpers.ts
> -export function logTxReceipt<T>(title: string, chainId: ChainId, txReceipt: T & { blockHash?: string; id?: string }) {
Also unrelated to the PR's goals, but then again an unused function, can be removed.

2024-12-05 22:54 UTC, 0xAlunara approved these changes

2024-12-06 03:39 UTC, OnlyJousting approved these changes

2024-12-06 07:20 UTC, merged